---
title: "HB"_discovery_april28"
output: html_document
date: "2023-04-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
pff_rush_12 <- read.csv("pff_rushing_summary_2012.csv")
pff_rush_13 <- read.csv("pff_rushing_summary_2013.csv")
pff_rush_14 <- read.csv("pff_rushing_summary_2014.csv")
pff_rush_15 <- read.csv("pff_rushing_summary_2015.csv")
pff_rush_16 <- read.csv("pff_rushing_summary_2016.csv")
pff_rush_17 <- read.csv("pff_rushing_summary_2017.csv")
pff_rush_18 <- read.csv("pff_rushing_summary_2018.csv")
pff_rush_19 <- read.csv("pff_rushing_summary_2019.csv")
pff_rush_20 <- read.csv("pff_rushing_summary_2020.csv")
pff_rush_21 <- read.csv("pff_rushing_summary_2021.csv")
pff_rush_22 <- read.csv("pff_rushing_summary_2022.csv")
pff_rec_12 <- read.csv("pff_receiving_summary_2012.csv")
pff_rec_13 <- read.csv("pff_receiving_summary_2013.csv")
pff_rec_14 <- read.csv("pff_receiving_summary_2014.csv")
pff_rec_15 <- read.csv("pff_receiving_summary_2015.csv")
pff_rec_16 <- read.csv("pff_receiving_summary_2016.csv")
pff_rec_17 <- read.csv("pff_receiving_summary_2017.csv")
pff_rec_18 <- read.csv("pff_receiving_summary_2018.csv")
pff_rec_19 <- read.csv("pff_receiving_summary_2019.csv")
pff_rec_20 <- read.csv("pff_receiving_summary_2020.csv")
pff_rec_21 <- read.csv("pff_receiving_summary_2021.csv")
pff_rec_22 <- read.csv("pff_receiving_summary_2022.csv")
combine <- read.csv("combine.csv")
salary <- read.csv("salary_data.csv")
pfr_rush_12 <- read.csv("2012_pfr_rushing.csv")
pfr_rush_13 <- read.csv("2013_pfr_rushing.csv")
pfr_rush_14 <- read.csv("2014_pfr_rushing.csv")
pfr_rush_15 <- read.csv("2015_pfr_rushing.csv")
pfr_rush_16 <- read.csv("2016_pfr_rushing.csv")
pfr_rush_17 <- read.csv("2017_pfr_rushing.csv")
pfr_rush_18 <- read.csv("2018_pfr_rushing.csv")
pfr_rush_19 <- read.csv("2019_pfr_rushing.csv")
pfr_rush_20 <- read.csv("2020_pfr_rushing.csv")
pfr_rush_21 <- read.csv("2021_pfr_rushing.csv")
pfr_rush_22 <- read.csv("2022_pfr_rushing.csv")
adp_12 <- read.csv("2012_fantasypros_rb_adp.csv")
adp_13 <- read.csv("2013_fantasypros_rb_adp.csv")
adp_14 <- read.csv("2014_fantasypros_rb_adp.csv")
adp_15 <- read.csv("2015_fantasypros_rb_adp.csv")
adp_16 <- read.csv("2016_fantasypros_rb_adp.csv")
adp_17 <- read.csv("2017_fantasypros_rb_adp.csv")
adp_18 <- read.csv("2018_fantasypros_rb_adp.csv")
adp_19 <- read.csv("2019_fantasypros_rb_adp.csv")
adp_20 <- read.csv("2020_fantasypros_rb_adp.csv")
adp_21 <- read.csv("2021_fantasypros_rb_adp.csv")
adp_22 <- read.csv("2022_fantasypros_rb_adp.csv")
oline_12 <- read_csv("2012 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_13 <- read_csv("2013 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_14 <- read_csv("2014 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_15 <- read_csv("2015 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_16 <- read_csv("2016 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_17 <- read_csv("2017 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_18 <- read_csv("2018 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_19 <- read_csv("2019 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_20 <- read_csv("2020 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_21 <- read_csv("2021 Basic Offensive Line Stats.csv", show_col_types=FALSE)
oline_22 <- read_csv("2022 Basic Offensive Line Stats.csv", show_col_types=FALSE)
dvoa_12 <- read_csv("2012 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_13 <- read_csv("2013 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_14 <- read_csv("2014 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_15 <- read_csv("2015 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_16 <- read_csv("2016 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_17 <- read_csv("2017 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_18 <- read_csv("2018 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_19 <- read_csv("2019 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_20 <- read_csv("2020 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_21 <- read_csv("2021 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
dvoa_22 <- read_csv("2022 Team DVOA Ratings Offense.csv", show_col_types=FALSE)
combine <- select(combine, -c(Pos, Team, School, Year))
pfr_rush_12 <- pfr_rush_12 %>% select(c(Player, Age, GS))
pfr_rush_13 <- pfr_rush_13 %>% select(c(Player, Age, GS))
pfr_rush_14 <- pfr_rush_14 %>% select(c(Player, Age, GS))
pfr_rush_15 <- pfr_rush_15 %>% select(c(Player, Age, GS))
pfr_rush_16 <- pfr_rush_16 %>% select(c(Player, Age, GS))
pfr_rush_17 <- pfr_rush_17 %>% select(c(Player, Age, GS))
pfr_rush_18 <- pfr_rush_18 %>% select(c(Player, Age, GS))
pfr_rush_19 <- pfr_rush_19 %>% select(c(Player, Age, GS))
pfr_rush_20 <- pfr_rush_20 %>% select(c(Player, Age, GS))
pfr_rush_21 <- pfr_rush_21 %>% select(c(Player, Age, GS))
pfr_rush_22 <- pfr_rush_22 %>% select(c(Player, Age, GS))
pff_rec_12 <- pff_rec_12 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_13 <- pff_rec_13 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_14 <- pff_rec_14 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_15 <- pff_rec_15 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_16 <- pff_rec_16 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_17 <- pff_rec_17 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_18 <- pff_rec_18 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_19 <- pff_rec_19 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_20 <- pff_rec_20 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_21 <- pff_rec_21 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
pff_rec_22 <- pff_rec_22 %>% select(-c(player_id, position, team_name, player_game_count, drops, 
                                       franchise_id, fumbles, grades_hands_drop, grades_hands_fumble,
                                       grades_offense, grades_pass_block, grades_pass_route, 
                                       receptions, routes, targets, yprr))
oline_12 <- oline_12 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_13 <- oline_13 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_14 <- oline_14 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_15 <- oline_15 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_16 <- oline_16 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_17 <- oline_17 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_18 <- oline_18 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_19 <- oline_19 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_20 <- oline_20 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_21 <- oline_21 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
oline_22 <- oline_22 %>%
  select(c(`Team`, `PowerSuccess`, `Stuffed`, `Adj. LineYards`, `RBYards`, `2nd LevelYards`, `Open FieldYards`)) %>%
  separate(col=PowerSuccess, into=c('PowerSuccess', NA), sep="%", convert=TRUE) %>%
  separate(col=Stuffed, into=c('Stuffed', NA), sep="%", convert=TRUE)
dvoa_12 <- dvoa_12 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_13 <- dvoa_13 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_14 <- dvoa_14 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_15 <- dvoa_15 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_16 <- dvoa_16 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_17 <- dvoa_17 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_18 <- dvoa_18 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_19 <- dvoa_19 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_20 <- dvoa_20 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_21 <- dvoa_21 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
dvoa_22 <- dvoa_22 %>%
  select(c(`Team`, `Total DVOA`, `Weighted DVOA`, `Pass DVOA`, `Rush DVOA`, `Variance`)) %>%
  separate(col=`Total DVOA`, into=c('Total_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Weighted DVOA`, into=c('Weighted_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Pass DVOA`, into=c('Pass_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Rush DVOA`, into=c('Rush_DVOA', NA), sep="%", convert=TRUE) %>%
  separate(col=`Variance`, into=c('Variance', NA), sep="%", convert=TRUE)
sal_12 <- salary %>%
  filter(X2012=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_13 <- salary %>% 
  filter(X2013=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_14 <- salary %>% 
  filter(X2014=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_15 <- salary %>% 
  filter(X2015=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_16 <- salary %>% 
  filter(X2016=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_17 <- salary %>% 
  filter(X2017=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_18 <- salary %>% 
  filter(X2018=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_19 <- salary %>% 
  filter(X2019=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_20 <- salary %>% 
  filter(X2020=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_21 <- salary %>% 
  filter(X2021=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
sal_22 <- salary %>% 
  filter(X2022=="TRUE") %>%
  group_by(Player) %>%
  summarise(Inlfated_Value=mean(Inflated.Value), Inflated_GTD=mean(Inflated.Guaranteed), Inflated_APY=mean(Inflated.APY), 
            Contract_Years=mean(Contract.Years), APY_percent=mean(APY..Of.Cap))
```

```{r}
pff_12 <- merge(pff_rush_12, pff_rec_12, by='player', all=T, suffixes=c("_rush", "_rec"))
pff_13 <- merge(pff_rush_13, pff_rec_13, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_14 <- merge(pff_rush_14, pff_rec_14, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_15 <- merge(pff_rush_15, pff_rec_15, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_16 <- merge(pff_rush_16, pff_rec_16, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_17 <- merge(pff_rush_17, pff_rec_17, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_18 <- merge(pff_rush_18, pff_rec_18, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_19 <- merge(pff_rush_19, pff_rec_19, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_20 <- merge(pff_rush_20, pff_rec_20, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_21 <- merge(pff_rush_21, pff_rec_21, by="player", all=T, suffixes=c("_rush", "_rec"))
pff_22 <- merge(pff_rush_22, pff_rec_22, by="player", all=T, suffixes=c("_rush", "_rec"))
rb_12 <- merge(pff_12, pfr_rush_12, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_13 <- merge(pff_13, pfr_rush_13, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_14 <- merge(pff_14, pfr_rush_14, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_15 <- merge(pff_15, pfr_rush_15, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_16 <- merge(pff_16, pfr_rush_16, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_17 <- merge(pff_17, pfr_rush_17, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_18 <- merge(pff_18, pfr_rush_18, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_19 <- merge(pff_19, pfr_rush_19, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_20 <- merge(pff_20, pfr_rush_20, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_21 <- merge(pff_21, pfr_rush_21, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_22 <- merge(pff_22, pfr_rush_22, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_12 <- merge(rb_12, adp_12, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_13 <- merge(rb_13, adp_13, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_14 <- merge(rb_14, adp_14, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_15 <- merge(rb_15, adp_15, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_16 <- merge(rb_16, adp_16, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_17 <- merge(rb_17, adp_17, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_18 <- merge(rb_18, adp_18, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_19 <- merge(rb_19, adp_19, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_20 <- merge(rb_20, adp_20, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_21 <- merge(rb_21, adp_21, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_22 <- merge(rb_22, adp_22, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_12 <- merge(rb_12, oline_12, by.x="team_name", by.y="Team", all=TRUE)
rb_13 <- merge(rb_13, oline_13, by.x="team_name", by.y="Team", all=TRUE)
rb_14 <- merge(rb_14, oline_14, by.x="team_name", by.y="Team", all=TRUE)
rb_15 <- merge(rb_15, oline_15, by.x="team_name", by.y="Team", all=TRUE)
rb_16 <- merge(rb_16, oline_16, by.x="team_name", by.y="Team", all=TRUE)
rb_17 <- merge(rb_17, oline_17, by.x="team_name", by.y="Team", all=TRUE)
rb_18 <- merge(rb_18, oline_18, by.x="team_name", by.y="Team", all=TRUE)
rb_19 <- merge(rb_19, oline_19, by.x="team_name", by.y="Team", all=TRUE)
rb_20 <- merge(rb_20, oline_20, by.x="team_name", by.y="Team", all=TRUE)
rb_21 <- merge(rb_21, oline_21, by.x="team_name", by.y="Team", all=TRUE)
rb_22 <- merge(rb_22, oline_22, by.x="team_name", by.y="Team", all=TRUE)
rb_12 <- merge(rb_12, dvoa_12, by.x="team_name", by.y="Team", all=TRUE)
rb_13 <- merge(rb_13, dvoa_13, by.x="team_name", by.y="Team", all=TRUE)
rb_14 <- merge(rb_14, dvoa_14, by.x="team_name", by.y="Team", all=TRUE)
rb_15 <- merge(rb_15, dvoa_15, by.x="team_name", by.y="Team", all=TRUE)
rb_16 <- merge(rb_16, dvoa_16, by.x="team_name", by.y="Team", all=TRUE)
rb_17 <- merge(rb_17, dvoa_17, by.x="team_name", by.y="Team", all=TRUE)
rb_18 <- merge(rb_18, dvoa_18, by.x="team_name", by.y="Team", all=TRUE)
rb_19 <- merge(rb_19, dvoa_19, by.x="team_name", by.y="Team", all=TRUE)
rb_20 <- merge(rb_20, dvoa_20, by.x="team_name", by.y="Team", all=TRUE)
rb_21 <- merge(rb_21, dvoa_21, by.x="team_name", by.y="Team", all=TRUE)
rb_22 <- merge(rb_22, dvoa_22, by.x="team_name", by.y="Team", all=TRUE)
rb_12 <- merge(rb_12, sal_12, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_13 <- merge(rb_13, sal_13, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_14 <- merge(rb_14, sal_14, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_15 <- merge(rb_15, sal_15, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_16 <- merge(rb_16, sal_16, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_17 <- merge(rb_17, sal_17, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_18 <- merge(rb_18, sal_18, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_19 <- merge(rb_19, sal_19, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_20 <- merge(rb_20, sal_20, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_21 <- merge(rb_21, sal_21, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_22 <- merge(rb_22, sal_22, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_12 <- merge(rb_12, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_13 <- merge(rb_13, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_14 <- merge(rb_14, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_15 <- merge(rb_15, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_16 <- merge(rb_16, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_17 <- merge(rb_17, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_18 <- merge(rb_18, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_19 <- merge(rb_19, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_20 <- merge(rb_20, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_21 <- merge(rb_21, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_22 <- merge(rb_22, combine, by.x="player", by.y="Player", all=T, match_type="fuzzy")
rb_12 <- filter(rb_12, position=="HB")
rb_13 <- filter(rb_13, position=="HB")
rb_14 <- filter(rb_14, position=="HB")
rb_15 <- filter(rb_15, position=="HB")
rb_16 <- filter(rb_16, position=="HB")
rb_17 <- filter(rb_17, position=="HB")
rb_18 <- filter(rb_18, position=="HB")
rb_19 <- filter(rb_19, position=="HB")
rb_20 <- filter(rb_20, position=="HB")
rb_21 <- filter(rb_21, position=="HB")
rb_22 <- filter(rb_22, position=="HB")
```

```{r}
rb_12 <- rb_12 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_13 <- rb_13 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_14 <- rb_14 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_15 <- rb_15 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_16 <- rb_16 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_17 <- rb_17 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_18 <- rb_18 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_19 <- rb_19 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_20 <- rb_20 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_21 <- rb_21 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)
rb_22 <- rb_22 %>% 
  mutate(fantasy_points = yards_rush*.1 + yards_rec*.1 + receptions*.5 + touchdowns_rec*6 + touchdowns_rush*6 - fumbles*2)

rb_12_13 <- merge(rb_12, rb_13, by="player", all=T, suffixes=c(".x", ".y"))
rb_13_14 <- merge(rb_13, rb_14, by="player", all=T, suffixes=c(".x", ".y"))
rb_14_15 <- merge(rb_14, rb_15, by="player", all=T, suffixes=c(".x", ".y"))
rb_15_16 <- merge(rb_15, rb_16, by="player", all=T, suffixes=c(".x", ".y"))
rb_16_17 <- merge(rb_16, rb_17, by="player", all=T, suffixes=c(".x", ".y"))
rb_17_18 <- merge(rb_17, rb_18, by="player", all=T, suffixes=c(".x", ".y"))
rb_18_19 <- merge(rb_18, rb_19, by="player", all=T, suffixes=c(".x", ".y"))
rb_19_20 <- merge(rb_19, rb_20, by="player", all=T, suffixes=c(".x", ".y"))
rb_20_21 <- merge(rb_20, rb_21, by="player", all=T, suffixes=c(".x", ".y"))
rb_21_22 <- merge(rb_21, rb_22, by="player", all=T, suffixes=c(".x", ".y"))
glimpse(rb_21_22)
```

```{r}
rb_12_22 <- rbind(rb_12_13, rb_13_14, rb_14_15, rb_15_16, rb_16_17, rb_17_18, rb_18_19, rb_19_20, rb_20_21, rb_21_22)
rb_12_22 <- rb_12_22 %>% select(c(player, player_game_count.x:fantasy_points.x, yards_rush.y, yards_rec.y, 
                                  receptions.y, touchdowns_rec.y, touchdowns_rush.y, fumbles.y, fantasy_points.y),
                                -c(rec_yards.x, franchise_id.x))
glimpse(rb_12_22)
```

```{r}
n=101
current_correl <- c()
future_correl <- c()
for (i in 2:n) {
  x <- cor(rb_12_22$fantasy_points.x, rb_12_22[,i], use="p")
  current_correl <- c(current_correl, x)
}
for (i in 2:n) {
  x <- cor(rb_12_22$fantasy_points.y, rb_12_22[,i], use="p")
  future_correl <- c(future_correl, x)
}
correl_df <- data.frame(factor=colnames(rb_12_22[,2:n]), current=current_correl, future=future_correl)
correl_df <- correl_df %>% mutate(perc_change=100*(future-current)/current)
best_correl <- correl_df %>% filter(future > 0.4 | future < -0.4)
good_correl <- correl_df %>% filter(future > 0.1 | future < -0.1)
bad_correl <- correl_df %>% filter(future < 0.1 & future > -0.1)
correl_df
best_correl
good_correl
bad_correl
```

```{r}
physical <- rb_12_22 %>% select(c(fantasy_points.y, Height.x, Weight.x, Dash40.x, Vertical.x, Bench.x, Broad.Jump.x, Cone3.x, 
                                  Shuttle.x, Age.x))
production <- rb_12_22 %>% select(c(fantasy_points.y, attempts.x, designed_yards.x, first_downs_rush.x, receptions.x, routes.x, 
                                    run_plays.x,targets.x, total_touches.x, touchdowns_rush.x, yards_rush.x, pass_plays.x, GS.x, 
                                    avoided_tackles_rush.x, breakaway_attempts.x, breakaway_yards.x, drops.x, elu_recv_mtf.x,
                                    elu_rush_mtf.x, touchdowns_rec.x, first_downs_rec.x, yards_after_catch.x, fumbles.x,
                                    fantasy_points.x))
efficiency <- rb_12_22 %>% select(c(fantasy_points.y, explosive.x, grades_offense.x, grades_pass.x, grades_run.x, longest_rush.x, 
                                    longest_rec.x,yco_attempt.x, ypa.x, targeted_qb_rating.x, yards_after_catch_per_reception.x, 
                                    elusive_rating.x, avg_depth_of_target.x, caught_percent.x, contested_catch_rate.x, drop_rate.x, 
                                    route_rate.x, slot_rate.x, yards_per_reception.x, yprr.x))
situation <- rb_12_22 %>% select(c(fantasy_points.y, Weighted_DVOA.x, Total_DVOA.x, Pass_DVOA.x, Rush_DVOA.x, Variance.x, PowerSuccess.x, 
                                   Stuffed.x, `Adj. LineYards.x`, RBYards.x, `2nd LevelYards.x`, `Open FieldYards.x`))
expectation <- rb_12_22 %>% select(c(fantasy_points.y, ADP.x, Pick.x, Appearances.x, AllAmerican.x, Inlfated_Value.x,
                                     Inflated_APY.x, Inflated_GTD.x, Contract_Years.x, APY_percent.x))
```

```{r}
modeller <- function(columns) {
  data <- rb_12_22 %>% select(c(columns, fantasy_points.y)) %>% na.omit()
  intercept_only <- lm(fantasy_points.y ~ 1, data=data)
  all <- lm(fantasy_points.y ~ ., data=data)
  model <- step(intercept_only, direction="forward", scope=formula(all), trace=0)
  summary(model)
}
modeller(colnames(expectation))
```

```{r}
big_names <- rb_12_22 %>% filter(fantasy_points.x>100)

x <- big_names$player %in% combine$Player
big_names$player[(big_names$player %in% combine$Player)]
no_names <- filter(rb_12_22, player!=x)
```



